

package interfaces;

import java.awt.Color;
import javax.swing.JOptionPane;


public class selborrow extends javax.swing.JFrame {

    public selborrow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnborrow = new javax.swing.JButton();
        btnrenew = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnborrow.setBackground(new java.awt.Color(204, 255, 204));
        btnborrow.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        btnborrow.setText("Borrow");
        btnborrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnborrowMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnborrowMouseExited(evt);
            }
        });
        btnborrow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrowActionPerformed(evt);
            }
        });
        jPanel1.add(btnborrow, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 150, 160));

        btnrenew.setBackground(new java.awt.Color(204, 255, 204));
        btnrenew.setFont(new java.awt.Font("Open Sans", 1, 18)); // NOI18N
        btnrenew.setText("Renew");
        btnrenew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnrenewMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnrenewMouseExited(evt);
            }
        });
        btnrenew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrenewActionPerformed(evt);
            }
        });
        jPanel1.add(btnrenew, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, 160));

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        jPanel1.add(btnback, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnborrowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrowActionPerformed
        int yesorno = JOptionPane.showConfirmDialog(null, "Are you sure you want to borrow books? ", "Borrowing", JOptionPane.YES_NO_OPTION);
        
        if(yesorno == 0){
        borrow bor = new borrow();
         bor.setVisible(true);
         // Remove this form (Home.java)
         this.dispose();
        }else{
            this.show();
        }
           
    }//GEN-LAST:event_btnborrowActionPerformed

    private void btnrenewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrenewActionPerformed
        int yesorno = JOptionPane.showConfirmDialog(null, "Are you sure you want to borrow books? ", "Borrowing", JOptionPane.YES_NO_OPTION);
        
        if(yesorno == 0){
       renew ren = new renew();
       //ren.lblindexno.setText(lblindexno.getText());
        ren.setVisible(true);
         // Remove this form (Home.java)
         this.dispose();
        }else{
            this.show();
        }
    }//GEN-LAST:event_btnrenewActionPerformed

    private void btnborrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnborrowMouseEntered
        btnborrow.setBackground(new Color(0,255,51));
    }//GEN-LAST:event_btnborrowMouseEntered

    private void btnrenewMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrenewMouseEntered
        btnrenew.setBackground(new Color(0,255,51));
    }//GEN-LAST:event_btnrenewMouseEntered

    private void btnborrowMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnborrowMouseExited
        btnborrow.setBackground(new Color(204,255,204));
    }//GEN-LAST:event_btnborrowMouseExited

    private void btnrenewMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnrenewMouseExited
       btnrenew.setBackground(new Color(204,255,204));
    }//GEN-LAST:event_btnrenewMouseExited

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        selection sel = new selection();
        sel.setVisible(true);
        
        // Remove this form (Home.java)
        this.dispose();
    }//GEN-LAST:event_btnbackActionPerformed

   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(selborrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(selborrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(selborrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(selborrow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new selborrow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnborrow;
    private javax.swing.JButton btnrenew;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
